### ISSUE TITLE
Prompt text field to use keyboard for entering email

### ISSUE THREAD

**Issue by jameBroa** [jameBroa/SDP-Group-2#28]
In the login page, the keyboard that pops up is generic. Can prompt the keyboard for email input (has the @ symbol on the bottom). See Below

![image](https://github.com/jameBroa/SDP-Group-2/assets/117519294/5dcb3103-c62a-4ae8-af2b-d7f0181c61be)

**Comment by bvechiato** [comment]
https://davidl.fr/blog/keyboard-react-native-ios-android?utm_campaign=thisweekinreact&utm_medium=email&utm_source=Revue%20newsletter
